config/routes.rb
Read50books::Application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :update] do
    resources :books
  end

  root 'pages#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title, :author, :date_completed, :user_id
  belongs_to :user

  def year
    self.date_completed.year
  end
end

app/models/book_search.rb
class BookSearch

  def initialize(search_string)
    @search_string = search_string
  end

  def perform
    @results = Array.new
    raw = client.search_books(@search_string).results
      unless raw == nil || raw.start_with?("\n")
        if raw.work.first.length > 2
          raw.work.each do |result|
            @results << GoodRead.new(result)
          end
        else
          @results << GoodRead.new(raw.work)
        end
      end
    @results
  end

  def id(id)
    @id = client.book(id)
  end

  protected

  def client
    @client = Goodreads::Client.new(:api_key => ENV['GOODREADS_KEY'], :api_secret => ENV['GOODREADS_SECRET'])
  end

end

app/models/good_read.rb
class GoodRead

  def initialize(hash)
    @hash = hash['best_book']
  end

  def id
    @hash['id']
  end

  def title
    @hash['title']
  end

  def author
    @hash['author']
  end

  def link
    @hash['link']
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :username, without: /\A\d/
  validates_uniqueness_of :username

  has_many :books, dependent: :destroy

  def self.find(input)
    input.to_i == 0 ? find_by_username(input) : super
  end

  def to_param
    username
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

    protected

  def authenticate_user
    unless user_signed_in?
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  def set_user
    @user = current_user
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user, only: [:create, :new]
  before_action :set_user

  def index
    @search = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.title == nil
      @search = BookSearch.new('')
      @book_hash = @search.id(@book.goodreads_id)
      @book.title = @book_hash.title
      if @book_hash.author == nil
        if @book_hash.authors.author.kind_of?(Array)
          @book.author = @book_hash.authors.author[0].name
        else
          @book.author = @book_hash.authors.author.name
        end
      else
        @book.author = @book_hash.author
      end
    end
    @book.user = @user
    if @book.save
      flash['success'] = "Nice work!"
      redirect_to user_book_path(@user, @book)
      award_badge(@user)
    else
      flash.now['alert'] = "Error! Please check your input and retry."
      render :new
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to user_path(@user)
  end

  def new
    search = BookSearch.new(params[:q])
    @results_collection = search.perform
    if @results_collection == []
      flash.now['warning'] = 'No results returned. Please enter information manually.'
    end
      @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    unless @book.goodreads_id == nil
      @search = BookSearch.new('')
      @book_hash = @search.id(@book.goodreads_id)
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(update_params)
      flash['success'] = "Book notes updated."
      redirect_to user_path(@user)
    else
      flash.now['alert'] = 'Error. Please check your input and retry.'
      render :show
    end
  end

  protected

  def award_badge(user)
    unless user.books == nil
      books = user.books.order(:date_completed)
      books_by_year = Hash.new
      books.each do |book|
        if books_by_year.has_key?(book.year)
          books_by_year[book.year] << book
        else
          books_by_year[book.year] = [book]
        end
      end
    end
    if books_by_year.values.last.size == 1
      flash['success'] = "Congratulations! You just read your first book of #{books_by_year.keys.last}. You get a badge!"
    elsif books_by_year.values.last.size == 5
      flash['success'] = "Congratulations! You read five books in #{books_by_year.keys.last}. You get a badge!"
    elsif books_by_year.values.last.size == 10
      flash['success'] = "Congratulations! You read ten books in #{books_by_year.keys.last}. You get a badge!"
    elsif books_by_year.values.last.size == 25
      flash['success'] = "Congratulations!!! You read twenty-five books in #{books_by_year.keys.last}. Halfway there! You get a badge!"
    elsif books_by_year.values.last.size == 25
      flash['success'] = "CONGRATULATIONS!!! You read fifty books in #{books_by_year.keys.last}! Unbelievable!"
    end
  end

  def book_params
    params.require(:book).permit(:author, :title, :date_completed, :user_id, :goodreads_id)
  end

  def update_params
    params.require(:book).permit(:brief, :note)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @gravatar_url = Gravatar.new(@user.email).image_url
    unless @user.books == nil
      @books = @user.books.order(:date_completed)
      @books_by_year = Hash.new
      @books.each do |book|
        if @books_by_year.has_key?(book.year)
          @books_by_year[book.year] << book
        else
          @books_by_year[book.year] = [book]
        end
      end
    end
    @facebook_share_url = 'http://www.read50books.com' + user_path(@user)
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(update_params)
      flash['success'] = "About #{@user.username} updated."
      redirect_to user_path(@user)
    else
      flash.now['alert'] = 'Error. Please check your input and retry.'
      render :show
    end
  end

  protected

  def update_params
    params.require(:user).permit(:about)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/new.html.haml
-content_for :title do
  -if user_signed_in?
    #{current_user.username} &ndash; Add New Book &ndash; Read 50 Books
  -else
    Add New Book &ndash; Read 50 Books
.row
  .small-11.medium-10.small-centered.columns
    -if user_signed_in?
      -if @results_collection == []
        =simple_form_for [current_user, @book] do |f|
          =f.input :title
          =f.input :author
          =f.label 'Date Completed'
          =f.date_select :date_completed
          =f.button :submit, 'Add Book'
      - else
        =simple_form_for [current_user, @book] do |f|
          =f.input :goodreads_id, collection: @results_collection, label: 'Select Book', include_blank: false
          %p
            Search results provided by #{link_to 'Goodreads', 'http://www.goodreads.com'}. Can't find the book you're looking for? #{link_to 'Click Here', new_user_book_path(@user, @book)}
          =f.label 'Date Completed'
          =f.date_select :date_completed
          =f.button :submit, 'Add Book'

app/views/books/show.html.haml
-content_for :title do
  #{@book.user.username} &ndash; #{@book.title} &ndash; Read 50 Books
.row
  .small-11.medium-8.small-centered.columns
    -if user_signed_in?
      -if @book_hash == nil
        .row
          .small-12.columns
            %h1
              #{@book.title}
            %h3
              by #{@book.author}
            %h5
              Completed On: #{@book.date_completed.to_date}
      -else
        .row
          .small-2.columns
            =link_to image_tag(@book_hash.image_url), @book_hash.link
            %span.secondary.label
              via #{link_to 'Goodreads', @book_hash.link}
          .small-10.columns
            %h1
              #{@book.title}
            %h3
              by #{@book.author}
            %h5
              Completed On: #{@book.date_completed.to_date}
      -if current_user == @book.user
        =simple_form_for [current_user, @book] do |f|
          =f.input :brief, placeholder: 'Visible to everyone'
          =f.input :note, placeholder: 'Visible only to you'
          %ul.inline-list
            %li
              =f.button :submit, class: "button small"
            %li
              =link_to "Remove Book", { action: "destroy", id: @book.id }, method: :delete, data: { confirm: "Are you sure?" }, class: "button small"
            %li
              =link_to 'Back To Your List', user_path(current_user), method: :get, class: "button small"
    -else
      .panel.radius
        %h4
          You must be #{link_to 'signed in', new_user_session_path} to view this content.

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title
      =content_for?(:title) ? yield(:title) : "Read 50 Books"
    =stylesheet_link_tag    "application"
    =javascript_include_tag "vendor/modernizr"
    =csrf_meta_tags
  %body
    %nav.top-bar{"data-topbar" => ""}
      %ul.title-area
        %li.name
          %h1
            =link_to 'Read 50 Books', root_path
        %li.toggle-topbar.menu-icon
          %a{:href => ""} Menu
      %section.top-bar-section
        %ul.right
          %li.divider
          -if user_signed_in?
            %li
              =link_to 'Account Settings', edit_user_registration_path
            %li.divider
          %li
            -if user_signed_in?
              =link_to 'Sign Out', destroy_user_session_path, method: :delete
            -else
              =link_to 'Sign In', new_user_session_path
          %li.divider
          %li
            -unless user_signed_in?
              =link_to 'Sign Up', new_user_registration_path
        %ul.left
          -if user_signed_in?
            %li
              =link_to 'My List', user_path(current_user)
    .row
      .small-12.columns
        %br/
        -flash.each do |name, msg|
          -if msg.is_a?(String)
            .alert-box{:class => name, "data-alert" => "", style: "font-size: large;"}
              -if name == 'alert'
                %i.fi-alert  
                =msg
              -elsif name == 'success'
                %i.fi-check  
                =msg
              -elsif name == 'warning'
                %i.fi-minus-circle
                =msg
              -else
                %i.fi-info 
                =msg
              %a.close{:href => "#"} ×
    %br/
    =yield
    .row
      .small-12.columns
        %p.legalese
          Read 50 Books is © 2014 Eben Lowe and is available under #{link_to 'the MIT License', 'http://opensource.org/licenses/MIT'}.
    =javascript_include_tag "application"

app/views/pages/index.html.haml
.row
  .small-11.medium-10.small-centered.columns
    - if user_signed_in?
      .panel.radius
        %p
          To get started, click the #{link_to 'My List', user_path(current_user)} link above. Enter the title of the book you wish to log, and then select the correct details from the search results. And happy reading!
    - else
      .panel.callout.radius
        %p
          On January 11th of 2014,
          %span.hard Read 50 Books
          was created during "Ship It Saturday", a one-day hack-a-thon organized by #{link_to 'Launch Academy', 'http://www.launchacademy.com'}. Coding started after breakfast and the site was deployed by dinnertime. Although some refactoring has taken place, the bulk of the work was completed in an 8-hour period.
        %p
          This site is currently in #{link_to 'open beta', 'http://en.wikipedia.org/wiki/Software_release_life_cycle'}, which means that it isn't finished yet. Everything works so far as I know, but you may encounter errors. I appreciate your patience and understanding as I get things ready for the full release.

app/views/users/show.html.haml
-content_for :title do
  #{@user.username} &ndash; Read 50 Books
.row
  .small-12.medium-2.medium-offset-1.columns
    %div
      =image_tag @gravatar_url, class: "th"
    %span.label
      =@user.username
    -unless @books_by_year.values.last == nil
      -if @books_by_year.values.last.size >= 1
        %h5
          = @books_by_year.keys.last
          Badges:
        %h5
          %i.fi-book
          1 book
        -if @books_by_year.values.last.size >= 5
          %h5
            %i.fi-star
            5 books
          -if @books_by_year.values.last.size >= 10
            %h5
              %i.fi-sheriff-badge
              10 books
            -if @books_by_year.values.last.size >= 25
              %h5
                %i.fi-trophy
                25 books
              -if @books_by_year.values.last.size >= 50
                %h5
                  %i.fi-crown
                  50 books
  .small-12.medium-6.columns.end
    %ul.inline-list
      %li Share this book list on Facebook:
      %li
        =social_share_button_tag(@user.username, url: @facebook_share_url)
    -if user_signed_in?
      -if current_user == @user
        =simple_form_for @user do |f|
          =f.input :about, label: false, placeholder: "About #{@user.username}"
          =f.button :submit, "Update 'About #{@user.username}'"
    -unless @user.about.nil?
      -unless @user.about.empty?
        .panel
          %p
            =@user.about
    %dl.tabs{"data-tab" => ""}
      -@books_by_year.each do |year, bookarray|
        %dd{ class: "#{'active' if year == @books_by_year.keys.last}" }
          #{link_to year, "#list-#{year}"}
    .tabs-content
      -@books_by_year.each do |year, bookarray|
        .content{ class: "#{'active' if year == @books_by_year.keys.last}", id: "list-#{year}"}
          -counter = 0
          %table
            %tbody
              -bookarray.each do |book|
                -counter += 1
                %tr
                  %td
                    =counter
                  %td
                    =link_to book.title, user_book_path(@user, book)
                    by #{book.author}
                    -if book.brief == nil
                    -else
                      %br/
                      %em{style: "margin-left: 1em;"}
                        #{book.brief}
    -if user_signed_in?
      -if current_user == @user
        =form_tag(new_user_book_path(current_user), method: "get") do
          =label_tag(:q, "Title:")
          =text_field_tag(:q)
          =submit_tag "Search", class: "button"